default_language_version:
  python: python3

repos:
- repo: https://github.com/asottile/pyupgrade
  rev: v3.15.0
  hooks:
  - id: pyupgrade
    args: ['--py38-plus']
- repo: https://github.com/pre-commit/pre-commit-hooks
  rev: v4.5.0
  hooks:
  - id: trailing-whitespace
  - id: end-of-file-fixer
    exclude: '.ipynb'
  - id: check-yaml
    args: ['--allow-multiple-documents']
  - id: debug-statements
- repo: https://github.com/adrienverge/yamllint.git
  rev: v1.33.0
  hooks:
  - id: yamllint
    args: ['--config-file=.yamllint.yaml']
- repo: https://github.com/psf/black
  rev: 23.11.0
  hooks:
  - id: black
- repo: https://github.com/pycqa/flake8
  rev: 6.1.0
  hooks:
  - id: flake8
    additional_dependencies: ['flake8-alphabetize', 'flake8-rst-docstrings']
- repo: https://github.com/PyCQA/isort
  rev: 5.12.0
  hooks:
  - id: isort
    args: ["--add_imports='from __future__ import annotations'"]
- repo: https://github.com/nbQA-dev/nbQA
  rev: 1.7.1
  hooks:
  - id: nbqa-black
    args: ['--target-version=py38']
  - id: nbqa-pyupgrade
    args: ['--py38-plus']
  - id: nbqa-isort
- repo: https://github.com/kynan/nbstripout
  rev: 0.6.1
  hooks:
  - id: nbstripout
    files: '.ipynb'
- repo: https://github.com/keewis/blackdoc
  rev: v0.3.9
  hooks:
  - id: blackdoc
    additional_dependencies: ['black==23.7.0']
- repo: https://github.com/python-jsonschema/check-jsonschema
  rev: 0.27.2
  hooks:
  - id: check-github-workflows
  - id: check-readthedocs
- repo: meta
  hooks:
  - id: check-hooks-apply

ci:
  autofix_commit_msg: |
    [pre-commit.ci] auto fixes from pre-commit.com hooks

    for more information, see https://pre-commit.ci
  autofix_prs: true
  autoupdate_branch: ''
  autoupdate_commit_msg: '[pre-commit.ci] pre-commit autoupdate'
  autoupdate_schedule: monthly
  skip: [nbstripout]
  submodules: false
